[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "beautifulsoup4>=4.14.2",
    "psycopg2-binary>=2.9.11",
    "python-telegram-bot>=22.5",
    "requests>=2.32.5",
]
